### ISSUE TITLE
ul/ol Differentiation

### ISSUE THREAD

**Issue by chryton** [mduvall/grande.js#32]
It seems that sometimes I start with an <ol>, even if I double return after the last element it will keep the ordered list tag rather than either starting over and/or allowing me to use a <ul>. I couldn't replicate it the other way around. It appears I would have otttriple return or soft return to get it to stop.

**Comment by mduvall** [comment]
It looks like there was some Markdown that made the formatting a bit funky. Anyway the issue seems to be that this type of list is producible?

```
1. Foo
2. Bar

1. Baz
```

If that's the case, that's how Medium currently supports lists (and I think it's moreso a limitation in the execCommand API). Please open the ticket again if that's not the issue, thanks!
