### ISSUE TITLE
Add UglifyJS to Gruntfile and task for minification

### ISSUE THREAD

**Issue by mduvall** [mduvall/grande.js#39]

**Comment by teemualap** [comment]
I would also suggest refactoring the project structure so that all of the source files (js/css/fonts) would be in a separate folder named src. Then building the actual minified grande in a build folder. I have an example of this in the build-process-ideas branch, though the build folder is named bundle.

Anyway, adding UglifyJS is a good idea. I could pr this immediately. Would you like to compile the minified js to the existing js folder for now? What about mangling?
